compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc
  os:
    - current
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.0.2.cjs
